import { MessageSquare, ChefHat } from "lucide-react";
import { ProductItem, Category } from '@/types/product'

export const menuItems: ProductItem[] = [
  {
    id: "95d583c6",
    name: "Veg Hakka Noodles with Veg Manchurian Gravy",
    description: "Made with homemade herbs. No MSG",
    price: 255,
    category: "combos",
    image: "/menuItems/VegHakkaNoodleswithVegManchurianGravy.webp",
    veg: true,
    popular: false,
    preparationTime: "35 mins",
  },
  {
    id: "4d63851e",
    name: "Non-Veg Hakka Noodles with Non-Veg Manchurian Gravy",
    description: "Delicious item prepared freshly",
    price: 345,
    category: "combos",
    image: "/menuItems/VegHakkaNoodles.webp",
    veg: false,
    popular: true,
    preparationTime: "35 mins",
  },
  {
    id: "bd2b1667",
    name: "Schezwan Fried Rice with Veg Manchurian Gravy",
    description: "Long grain rice with fresh bell peppers",
    price: 255,
    category: "combos",
    image: "/menuItems/",
    veg: true,
    popular: false,
    preparationTime: "35 mins",
  },
  {
    id: "bf2b6a19",
    name: "Schezwan Fried Rice with Non-Veg Manchurian Gravy",
    description: "Delicious item prepared freshly",
    price: 345,
    category: "combos",
    image: "/menuItems/SchezwanFriedRice.webp",
    veg: false,
    popular: false,
    preparationTime: "15 mins",
  },
  {
    id: "82503880",
    name: "Lauki Kofta with 2 Parathas",
    description: "Four creamy kofta balls in tomato gravy with fresh cream",
    price: 250,
    category: "combos",
    image: "/menuItems/",
    veg: true,
    popular: false,
    preparationTime: "35 mins",
  },
  {
    id: "8213b863",
    name: "Paneer Pasanda Gravy + 2 Parathas",
    description: "Makhani Gravy with chef's special masala",
    price: 295,
    category: "combos",
    image: "/menuItems/",
    veg: true,
    popular: false,
    preparationTime: "15 mins",
  },
  {
    id: "bfe44c04",
    name: "Paneer Lajawab Roll",
    description:
      "Roll made with fresh juicy paneer, red bell pepper, onion and a variety of sauces",
    price: 195,
    category: "rocking-rolls",
    image: "/menuItems/ChickenRoll.webp",
    veg: true,
    popular: true,
    preparationTime: "25 mins",
  },
  {
    id: "0affba65",
    name: "Chicken Roll",
    description: "Made with boneless chicken in variety of sauces",
    price: 200,
    category: "rocking-rolls",
    image: "/menuItems/ChickenRoll.webp",
    veg: false,
    popular: false,
    preparationTime: "30 mins",
  },
  {
    id: "0eaded49",
    name: "Egg Roll",
    description: "Made in Kolkata style",
    price: 165,
    category: "rocking-rolls",
    image: "/menuItems/ChickenRoll.webp",
    veg: false,
    popular: false,
    preparationTime: "40 mins",
  },
  {
    id: "c1ab8687",
    name: "Chicken Curry",
    description: "Cooked in onion, tomato and Indian spices",
    price: 250,
    category: "main-course",
    image: "/menuItems/ChickenCurry.webp",
    veg: false,
    popular: true,
    preparationTime: "15 mins",
  },
  {
    id: "b53e2f19",
    name: "Egg Curry",
    description: "4 boiled eggs in curry of onion, tomato, and curd",
    price: 250,
    category: "main-course",
    image: "/menuItems/ChickenCurry.webp",
    veg: false,
    popular: false,
    preparationTime: "20 mins",
  },
  {
    id: "04324ad5",
    name: "Dahi Khichdi with Curd",
    description: "Made with rice, moong dal, dahi and seasonal vegetables",
    price: 200,
    category: "main-course",
    image: "/menuItems/",
    veg: true,
    popular: true,
    preparationTime: "25 mins",
  },
  {
    id: "1d4f9db4",
    name: "Fish Curry (Dal Maach)",
    description:
      "4 big pieces of fish, Bengali-style cooked in curd and spices",
    price: 540,
    category: "main-course",
    image: "/menuItems/FishCurry.webp",
    veg: false,
    popular: false,
    preparationTime: "20 mins",
  },
  {
    id: "b2db8a8d",
    name: "Veg Hakka Noodles",
    description: "Made with fresh vegetables and herbs. No MSG",
    price: 155,
    category: "chinese",
    image: "/menuItems/VegHakkaNoodles.webp",
    veg: true,
    popular: false,
    preparationTime: "20 mins",
  },
  {
    id: "914e7291",
    name: "Non-Veg Hakka Noodles",
    description: "Delicious item prepared freshly",
    price: 250,
    category: "chinese",
    image: "/menuItems/VegHakkaNoodles.webp",
    veg: false,
    popular: true,
    preparationTime: "20 mins",
  },
  {
    id: "9c7ec32f",
    name: "Veg Schezwan Fried Rice",
    description: "Chef's special masala, Long Grain rice, fresh vegetables",
    price: 155,
    category: "chinese",
    image: "/menuItems/SchezwanFriedRice.webp",
    veg: true,
    popular: true,
    preparationTime: "40 mins",
  },
  {
    id: "2839e182",
    name: "Non-Veg Schezwan Fried Rice",
    description: "Delicious item prepared freshly",
    price: 250,
    category: "chinese",
    image: "/menuItems/SchezwanFriedRice.webp",
    veg: false,
    popular: false,
    preparationTime: "35 mins",
  },
  {
    id: "53342947",
    name: "Manchurian Gravy (Veg/Non-Veg)",
    description: "Tangy and tasty gravy",
    price: 150,
    category: "chinese",
    image: "/menuItems/",
    veg: false,
    popular: false,
    preparationTime: "35 mins",
  },
  {
    id: "7519897c",
    name: "Fish Fry (4 PCS)",
    description: "Indian style fried fish with side vegetables",
    price: 485,
    category: "chinese",
    image: "/menuItems/FishFry.webp",
    veg: false,
    popular: false,
    preparationTime: "35 mins",
  },
  {
    id: "914a8118",
    name: "Khichdi Chawal / Roti",
    description: "Made in fresh curd with basmati rice / tawa roti",
    price: 140,
    category: "economy-meals",
    image: "/menuItems/",
    veg: true,
    popular: true,
    preparationTime: "40 mins",
  },
  {
    id: "c3e70d78",
    name: "Chole / Rajma with Chawal / Roti",
    description: "Rajma or chole in special masala with juicy gravy",
    price: 140,
    category: "economy-meals",
    image: "/menuItems/",
    veg: true,
    popular: true,
    preparationTime: "25 mins",
  },
  {
    id: "6a14b8c1",
    name: "Dal Makhani with 2 Parathas / Roti",
    description: "Traditional Dal Makhani with parathas or roti",
    price: 140,
    category: "economy-meals",
    image: "/menuItems/",
    veg: true,
    popular: false,
    preparationTime: "40 mins",
  },
];

export const processSteps = [
  {
    step: 1,
    title: "Browse Menu",
    description:
      "Explore our daily fresh menu with authentic home-style dishes",
    icon: ChefHat,
    color: "bg-saffron",
  },
  {
    step: 2,
    title: "Fill Your Details",
    description: "Add your contact information and delivery address",
    icon: MessageSquare,
    color: "bg-saffron-light",
  },
  {
    step: 3,
    title: "Send Order on WhatsApp",
    description: "Complete your order through our convenient WhatsApp system",
    icon: MessageSquare,
    color: "bg-saffron-dark",
  },
];

export const categories: Category[] = [
    { id: 'all', name: 'All Items', icon: '🍽️' },                    // General dining
    { id: 'rocking-rolls', name: `ROCKING ROLLS`, icon: '🌯' },      // Burrito/Wrap (rolls)
    { id: 'combos', name: 'COMBOS', icon: '🍱' },                    // Bento box (combo meals)
    { id: 'chinese', name: `CHINESE`, icon: '🥢' },                  // Chopsticks
    { id: 'main-course', name: `MAIN COURSE`, icon: '🍛' },          // Curry rice plate
    { id: 'economy-meals', name: `ECONOMY MEALS`, icon: '💰' },      // Money bag for budget meals
  ];

